# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - runner:
        # 自定义CPU核心数,最大支持64核
        cpus: 64
      docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      stages:
        - name: 环境启动时执行以下命令
          script:
        # 安装pnpm并使用pnpm安装依赖
            - npm install -g pnpm
            - pnpm i
            - pnpm docs:dev

# 云原生构建流程和自动部署
main:
  push:
    - imports: https://cnb.cool/W3C/Hyde/APIToken/-/blob/main/APIToken.yml
      stages:
        - name: 构建当前项目
          image: node:22
          script: npm install -g pnpm && pnpm i && pnpm run docs:build
        - name: 部署到Pages
          image: node:22
          script: npx edgeone pages deploy ./docs/.vitepress/dist --name vitepress-theme-teek --token $EDGEONE_PAGES_API_TOKEN